version: "3.8"
services:
  web:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - database
  redis:
    image: redis:latest
  database:
    image: mongo:latest
    container_name: "mongodb_data_container"    
    volumes:
        - mongodb_data_container:/data/db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=rootpassword
        - MONGO_INITDB_DATABSE=TODO-DB
    ports:
        - 27017:27017
volumes:
    mongodb_data_container: