version: "3.8"
services:
  eros:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - database
  redis:
    image: redis:latest
    container_name: "redis_data_container"
    volumes:
      - redis_data_container:/redis/data/db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL    
    ports: 
      -  6379:6379 
  database:
    image: mongo:latest
    container_name: "mongodb_data_container"    
    volumes:
        - mongodb_data_container:/mongodb/data/db
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        #- MONGO_INITDB_ROOT_USERNAME=root
        #- MONGO_INITDB_ROOT_PASSWORD=rootpassword
        - MONGO_INITDB_DATABSE=TODO-DB
    ports:
        - 27017:27017
volumes:
    redis_data_container:
      driver: local
    mongodb_data_container: